#!/usr/bin/env fish

set -g TESTS 0
set -g PASSED 0
set -g FAILED 0
function fail
    set -g TESTS (math 1 + $TESTS)
    set -g FAILED (math 1 + $FAILED)
    set_color red
    echo -e "❌ test failed\n"
    set_color normal
end
function pass
    set -g TESTS (math 1 + $TESTS)
    set -g PASSED (math 1 + $PASSED)
    set_color green
    echo -e "✓ test passed\n"
    set_color normal
end
source ./lib/k8s.fish
# run tests against the staging cluster
set -gx NS moo-stg1
set -gx POD (get_pod)

# create backup
function create
    check_namespace
    set_color --bold
    echo -e "\tCreate a backup file on the Moodle pod...\n"
    set_color normal
    # ep test course https://moodle-stg-1.cca.edu/course/view.php?id=3606
    ./backup.fish mk 3606
    kubectl exec -n$NS $POD -- ls /bitnami/moodledata/backups/ | grep backup_3606 2&>/dev/null
    if test $status -eq 0
        pass
    else
        fail
    end
    kubectl exec -n$NS $POD -- sh -c 'rm /bitnami/moodledata/backups/backup_3606*'
end

# download backup
function download
    check_namespace
    true
end

# copy backup to GSB
function copy
    set_color --bold
    echo -e "\tCopy a backup file to GSB...\n"
    set_color normal
    set FILE backup_2666_TESTS-101-01-2666TE_2022.06.21.mbz
    touch test/$FILE
    set SEMESTER 2666TE
    ./backup.fish cp $SEMESTER ./test/$FILE
    gsutil ls gs://moodle-course-archive/$SEMESTER/$FILE
    if test $status -eq 0
        pass
    else
        fail
    end
    gsutil rm gs://moodle-course-archive/$SEMESTER/$FILE 2&>/dev/null
end

# delete backup & course from pod
function delete
    check_namespace
    true
end

echo "It should..."
# make individual tests runnable
switch $argv[1]
    case ''
        create
        download
        copy
        delete
    case create
        create
    case download
        download
    case copy
        copy
    case delete
        delete
end

# summarize results
set_color --bold
echo -n "$PASSED/$TESTS tests passed."
if test $FAILED -gt 0
    set_color red
    echo " $FAILED failure(s) - see results above."
else
    # trailing newline
    echo
end
set_color normal
